# Generated by Django 4.1 on 2022-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='username')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, verbose_name='email')),
            ],
        ),
    ]
