# Generated by Django 4.1 on 2022-08-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claimExpense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=20, null=True, verbose_name='description')),
                ('amount', models.IntegerField(blank=True, max_length=4, null=True, verbose_name='amount')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
            ],
        ),
    ]
